language: ruby
rvm:
- 2.4.0
addons:
  postgresql: '9.4'
before_script:
- psql --version
- psql -c 'SELECT version();' -U postgres
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rake test:prepare
- bundle exec rake db:migrate --trace
- bin/rails db:migrate RAILS_ENV=test
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: B/nQrgor7pWQwsVGNnU5x3Oldhp50/d9BeT5h9LyAw+BgTwxgrMOwG2feXKGz55HgxzbFp/WncTp8AlLl87uUGSUNKf5VbeUrn2ygHhn/bCiyDz1rsNKZ1deQG5zBaMc8mxZUxH/34p0HRDnM83loA4qt1lByUsRKNRs2gQJmXREBLicVHOz6oJNsHkafRPPO8a3y1lH9xFyxV1gBhI7EHphtwWIhUx0UKHfmhYWWgiQ/5qOXUAwhHaVdoXjgti6lN/agmymlrOo5/Qo8TKc7gLQDN9UUg9ItPmFBzX6wG/Y9zM9zz+mvgr6bWHcERqnLJGpS97gZ1E+l1wojkVjjn8JafR02XqZSvb6LwW3LYfHDHy/hYGXdDstOXnVKbfEHnzrI9BepsNdrbvqKZecP2xGKKkGRHWFCwXrqMQBqLlzZ/q4gjub61M1lANPiqbUpM+r1ApHVNB4cb7feC0g1QrWTareSNKppSYdmr9hJF0MVG7bsC8t9k2++0dZBdGLr+oJDOOIOixeD9P4oiQyq8bB+18B3XZoAIuZqCJCnfVopnSdCSUuMfB350mPCOVFCH6RtC7KIhtoyx3v5ITaL5NIaIdudD3L+naIFIBsJR6rXLRUxoCDaAKienlkxHuvw9PaMJpZEcy2vdsTJOaZpdKBFF+zE6aPo54x59N9M9M=
  app: ppokerapp
  run: rake db:migrate
