language: ruby
rvm:
- 2.4.0
addons:
   postgresql: "9.4"
before_script:
-  psql --version
-  psql -c 'SELECT version();' -U postgres
-  cp config/database.yml.travis config/database.yml
-  psql -c 'create database travis_ci_test;' -U postgres
script:
 - bundle exec rake test:prepare
 - bundle exec rake db:migrate --trace
 - bin/rails db:migrate RAILS_ENV=test
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rspec -fd spec/
